'use strict';
const $=id=>document.getElementById(id);
let running=false,loading=false,paused=false,db,records=[],romVersion='ko';
const ROM_HASH='B85F5970EA619B7A6671A4DE8CCE430E2654A2E5BBEF5E74EF35D4702DADB67B';
$('game').innerHTML='<div class="welcome"><div class="moon">☾</div><h2>Another Story</h2><p>세일러 전사들과 함께하는 원작 RPG.<br>게임 시작을 눌러 바로 플레이하세요.</p></div>';
function message(text){$('message').textContent=text;}
function manager(){if(!running)throw Error('먼저 게임을 시작해 주세요.');return window.EJS_emulator.gameManager;}
function transact(mode,action){return new Promise((resolve,reject)=>{const tx=db.transaction('slots',mode);let value;action(tx.objectStore('slots'),x=>value=x);tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
const dbReady=new Promise((resolve,reject)=>{const req=indexedDB.open('sailor-another-story-web',1);req.onupgradeneeded=()=>req.result.createObjectStore('slots',{keyPath:'id'});req.onsuccess=()=>{db=req.result;resolve();};req.onerror=()=>reject(req.error);});
async function refreshSlots(){await dbReady;records=await transact('readonly',(s,set)=>{s.getAll().onsuccess=e=>set(e.target.result);});$('slots').replaceChildren();for(let i=1;i<=3;i++){const row=document.createElement('div');row.className='slot';const item=records.find(x=>x.id===romVersion+'-'+i);const name=document.createElement('span');name.className='slot-name';name.textContent='슬롯 '+i;const time=document.createElement('span');time.className='slot-time';time.textContent=item?new Date(item.time).toLocaleString('ko-KR'):'비어 있음';name.append(time);const save=document.createElement('button');save.textContent='저장';save.disabled=!running;save.onclick=()=>saveSlot(i);const load=document.createElement('button');load.textContent='불러오기';load.disabled=!running||!item;load.onclick=()=>loadSlot(i);row.append(name,save,load);$('slots').append(row);} $('export').disabled=!records.length;}
async function saveSlot(i){try{const state=manager().getState();await transact('readwrite',s=>s.put({id:romVersion+'-'+i,version:romVersion,hash:ROM_HASH,time:Date.now(),state:Array.from(state)}));await refreshSlots();message('슬롯 '+i+'에 저장했어요.');}catch(e){message('저장 실패: '+e.message);}}
async function loadSlot(i){try{const item=records.find(x=>x.id===romVersion+'-'+i);if(!item)throw Error('저장된 장면이 없어요.');manager().loadState(new Uint8Array(item.state));message('슬롯 '+i+'을 불러왔어요.');}catch(e){message('불러오기 실패: '+e.message);}}
function pause(){if(!running)return;releaseAll();paused=!paused;window.EJS_emulator[paused?'pause':'play']();$('pause').textContent=paused?'계속하기':'일시정지';$('state').textContent=paused?'일시정지':'플레이 중';}
function controls(){const keys=['x','s','shift','enter','up arrow','down arrow','left arrow','right arrow','z','a','q','e'];const pads=['BUTTON_2','BUTTON_4','SELECT','START','DPAD_UP','DPAD_DOWN','DPAD_LEFT','DPAD_RIGHT','BUTTON_1','BUTTON_3','LEFT_TOP_SHOULDER','RIGHT_TOP_SHOULDER'];return {0:Object.fromEntries(keys.map((value,i)=>[i,{value,value2:pads[i]}])),1:{},2:{},3:{}};}
async function launch(){if(loading||running)return;loading=true;window.selectedGameUrl='game-ko.sfc?v=direct1';romVersion=$('edition').value;$('edition').disabled=true;$('launch').disabled=true;$('launch').textContent='게임 준비 중…';$('state').textContent='게임 불러오는 중';$('game').replaceChildren();Object.assign(window,{EJS_player:'#game',EJS_core:'snes',EJS_gameUrl:window.selectedGameUrl,EJS_startOnLoaded:true,EJS_pathtodata:'data/',EJS_gameName:'Sailor Moon Another Story '+romVersion,EJS_gameID:romVersion==='jp'?19950922:19950923,EJS_language:'ko-KR',EJS_disableAutoLang:true,EJS_startButtonName:'원작 게임 시작',EJS_color:'#efafcf',EJS_volume:Number($('volume').value)/100,EJS_defaultControls:controls(),EJS_disableDatabases:true,EJS_noAutoFocus:false,EJS_Buttons:{cheat:false,saveState:false,loadState:false,saveSavFiles:true,loadSavFiles:true,exitEmulation:false},EJS_defaultOptions:{'save-state-location':'download'},EJS_ready:()=>{$('state').textContent='게임 준비 중';message('게임을 준비하고 있어요. 잠시 기다려 주세요.');},EJS_onGameStart:()=>{running=true;loading=false;$('state').textContent='플레이 중';$('launch').textContent='실행 중';$('pause').disabled=false;$('fullscreen').disabled=false;refreshSlots();message('화면 아래 버튼으로 이동·대화·메뉴를 조작하세요. 키보드도 사용할 수 있어요.');}});const script=document.createElement('script');script.src='data/loader.js';script.onerror=()=>{loading=false;$('edition').disabled=false;$('launch').disabled=false;message('에뮬레이터를 불러오지 못했어요. 페이지를 새로고침해 주세요.');};document.body.append(script);}
$('launch').onclick=launch;$('pause').onclick=pause;$('fullscreen').onclick=()=>{const panel=document.querySelector('.console');if(document.fullscreenElement)document.exitFullscreen();else if(panel.requestFullscreen)panel.requestFullscreen().catch(()=>message('이 브라우저에서 전체화면을 열 수 없어요.'));else message('이 브라우저에서는 일반 화면의 조작 버튼으로 플레이해 주세요.');};
$('volume').oninput=()=>{const v=Number($('volume').value);$('volumeLabel').textContent=v+'%';try{localStorage.setItem('another-story-volume',v);}catch{}if(running){window.EJS_emulator.volume=v/100;window.EJS_emulator.setVolume(v/100);}};
try{const stored=localStorage.getItem('another-story-volume');if(stored!==null){$('volume').value=Math.max(0,Math.min(100,Number(stored)||0));$('volumeLabel').textContent=$('volume').value+'%';}}catch{}
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({format:'sailor-another-story-save-v1',hash:ROM_HASH,slots:records})],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='sailor-another-story-saves.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('백업 다운로드를 요청했어요.');};
$('import').onclick=()=>$('backupFile').click();$('backupFile').onchange=async()=>{try{const file=$('backupFile').files[0];if(!file)return;if(file.size>12*1024*1024)throw Error('백업 파일이 너무 커요.');const data=JSON.parse(await file.text());if(data.format!=='sailor-another-story-save-v1'||data.hash!==ROM_HASH||!Array.isArray(data.slots)||data.slots.length>6)throw Error('이 게임의 저장 백업이 아니에요.');for(const row of data.slots){if(!/^(jp|ko)-[123]$/.test(row.id)||row.hash!==ROM_HASH||!Array.isArray(row.state)||!row.state.length||row.state.length>2000000||row.state.some(v=>!Number.isInteger(v)||v<0||v>255)||!Number.isFinite(row.time))throw Error('저장 데이터가 올바르지 않아요.');}await dbReady;await transact('readwrite',s=>data.slots.forEach(row=>s.put(row)));await refreshSlots();message('저장 백업을 복원했어요.');}catch(e){message('백업 불러오기 실패: '+e.message);}finally{$('backupFile').value='';}};
const holds=new Map(),pressTimes=new Map(),releaseTimers=new Map(),keyInputs=new Map();
function pressInput(index,source){if(!running||paused)return;clearTimeout(releaseTimers.get(index));releaseTimers.delete(index);let sources=holds.get(index);if(!sources){sources=new Set();holds.set(index,sources);pressTimes.set(index,performance.now());manager().simulateInput(0,index,1);}sources.add(source);}
function releaseInput(index,source){const sources=holds.get(index);if(!sources)return;sources.delete(source);if(sources.size)return;const wait=Math.max(0,100-(performance.now()-pressTimes.get(index)));releaseTimers.set(index,setTimeout(()=>{if(holds.get(index)?.size)return;if(running)manager().simulateInput(0,index,0);holds.delete(index);pressTimes.delete(index);releaseTimers.delete(index);paintControls();},wait));}
function releaseAll(){for(const timer of releaseTimers.values())clearTimeout(timer);for(const index of holds.keys())if(running)manager().simulateInput(0,index,0);holds.clear();pressTimes.clear();releaseTimers.clear();keyInputs.clear();paintControls();}
const controller=document.querySelector('.controller');
document.querySelector('.console-foot').before(controller);
const padButtons=[...controller.querySelectorAll('[data-input]')];
for(const button of padButtons)button.addEventListener('click',()=>{const index=Number(button.dataset.input);if(!running||paused||holds.get(index)?.size)return;pressInput(index,'accessible-click');releaseInput(index,'accessible-click');paintControls();});
function paintControls(){for(const button of padButtons){const index=Number(button.dataset.input);button.disabled=!running||paused;button.classList.toggle('held',Boolean(holds.get(index)?.size));button.setAttribute('aria-pressed',String(Boolean(holds.get(index)?.size)));}}
for(const button of padButtons){const index=Number(button.dataset.input);button.addEventListener('contextmenu',e=>e.preventDefault());button.addEventListener('pointerdown',e=>{if(!running||paused||e.button!==0)return;e.preventDefault();button.setPointerCapture(e.pointerId);pressInput(index,'p'+e.pointerId);paintControls();});for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,e=>{releaseInput(index,'p'+e.pointerId);paintControls();});button.addEventListener('keydown',e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();pressInput(index,'button');paintControls();}});button.addEventListener('keyup',e=>{if(e.key===' '||e.key==='Enter'){releaseInput(index,'button');paintControls();}});}
// A tap confirms dialogue; movement uses the directional pad, including held input.
let screenTap;
$('game').addEventListener('pointerdown',e=>{if(!running||paused||e.button!==0||!e.target.matches('canvas'))return;screenTap={id:e.pointerId,x:e.clientX,y:e.clientY};});
$('game').addEventListener('pointerup',e=>{if(screenTap?.id!==e.pointerId)return;const tap=screenTap;screenTap=null;if(e.target.matches('canvas')&&Math.hypot(e.clientX-tap.x,e.clientY-tap.y)<15){pressInput(8,'screen');releaseInput(8,'screen');}});
$('game').addEventListener('pointercancel',()=>{screenTap=null;});
new MutationObserver(paintControls).observe($('state'),{childList:true});
paintControls();
document.addEventListener('keydown',e=>{const emulator=window.EJS_emulator;if(!running||paused||!e.target.closest('.ejs_parent')||e.target.matches('input,textarea,select,button')||emulator.isPopupOpen()||emulator.settingsMenu.style.display!=='none')return;const entry=Object.entries(emulator.controls[0]).find(([index,control])=>Number(index)<12&&control.value===e.keyCode);if(!entry)return;e.preventDefault();e.stopImmediatePropagation();if(e.repeat)return;const index=Number(entry[0]);keyInputs.set(e.code,index);pressInput(index,'k'+e.code);},true);
document.addEventListener('keyup',e=>{const index=keyInputs.get(e.code);if(index===undefined)return;e.preventDefault();e.stopImmediatePropagation();keyInputs.delete(e.code);releaseInput(index,'k'+e.code);},true);
window.addEventListener('blur',releaseAll);document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused)pause();});
refreshSlots().catch(()=>message('이 브라우저에서 저장 공간을 사용할 수 없어요.'));

function editionChanged(){romVersion=$('edition').value;$('versionLabel').textContent=romVersion==='ko'?'한국어 대사 초안 · 14,127줄':'일본어 원작';$('coverage').textContent=romVersion==='ko'?'스토리 대사 14,127줄과 메뉴·아이템·기술·프로필을 한글화했습니다. 자동 번역 초안이며 일부 이미지 글자와 전투창은 일본어입니다.':'게임 내부 대사와 메뉴를 원작 일본어로 실행합니다.';refreshSlots();}
$('edition').onchange=editionChanged;editionChanged();


